name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  buildTest:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-13 ]
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - uses: gradle/wrapper-validation-action@v3.5.0
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Debug keystore
        run: keytool -genkey -v -keystore app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
      - name: Build project
        run: ./gradlew assemble :library:build
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
      - name: Run tests
        run: ./gradlew test
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: ./gradlew cAT
          api: 28
          tag: default
          abi: x86
          cmdOptions: -noaudio -no-boot-anim -no-window -metrics-to-console
      - name: Archive screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: DocumentScanner-Screenshots
          if-no-files-found: error
          path: |
            app/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
            app/build/outputs/androidTest-results/connected
      - name: Archive Espresso results
        uses: actions/upload-artifact@v4.6.2
        with:
          if-no-files-found: error
          name: DocumentScanner-Espresso-report
          path: app/build/reports/androidTests/connected
  Check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-14 ]
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Code checks
        run: ./gradlew lint ktLintcheck
      - name: Archive Lint report
        uses: actions/upload-artifact@v4.6.2
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: DocumentScanner-Lint-report
          path: app/build/reports/lint-results*.html
