name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  buildTest:
    name: Build & Test JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [ 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Debug keystore
        run: keytool -genkey -v -keystore app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
      - name: Build project
        run: ./gradlew assembleDebug
      - name: Run tests
        run: ./gradlew test
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
        with:
          cmd: ./gradlew cAT
          api: 28
          tag: default
          abi: x86
          cmdOptions: -noaudio -no-boot-anim -no-window
      - name: Archive Espresso results
        uses: actions/upload-artifact@v3
        with:
          name: DocumentScanner-Espresso-report
          path: app/build/reports/androidTests/connected
      - name: Save logcat output
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: DocumentScanner-logcat
          path: artifacts/logcat.log
      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        with:
          name: DocumentScanner-Screenshots
          path: screenshots/adb
  Check:
    name: Check
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [ 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Code checks
        run: ./gradlew lint
      - name: Archive Lint report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: DocumentScanner-Lint-report
          path: app/build/reports/lint-results.html
