name: Update Gradle Wrapper

on:
  schedule:
    - cron: "15 6 * * WED"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2.1.0
        with:
          repo-token: ${{ secrets.GITHUBTOKEN }}
          set-distribution-checksum: false
