name: Update Gradle Wrapper

on:
  schedule:
    - cron: "15 6 * * WED"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.17
        with:
          repo-token: ${{ secrets.GITHUBTOKEN }}
          set-distribution-checksum: false
